development:
  adapter: sqlite3
  database: db/blog_dev
  timeout: 5000


test:
  adapter: postgresql
  database: blog_test
  username: 
  password: 
  host: localhost

production:
  adapter: postgresql
  database: blog_live
  username: 
  password: 
  host: localhost

