development:
  adapter: postgresql
  database: blog_development
  username: 
  password: 
  host: localhost

test:
  adapter: postgresql
  database: blog_test
  username: 
  password: 
  host: localhost

production:
  adapter: postgresql
  database: blog_live
  username: 
  password: 
  host: localhost

